server:
  port: 9001
  servlet:
    context-path: /stayvigo

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    root: info

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

test:
  token: test

security:
  basic:
    enabled: false